### ISSUE TITLE
Autonomously switch to option panels

### ISSUE THREAD

**Issue by yepw** [uwgraphics/MotionComparator#14]
When users click on a 3D scene, robot or time-series plot, the interface autonomously switches tabs to open the corresponding option panel. This is a good feature most of the time. However, when a visualization and its option panel are in the same sub-window, this will hide the visualization and switch to the option panel. There are two ways to fix it:
1. Lock option panels so that users can not put visualizations and option panels in the same sub-window
2. Disable the autonomous tab switch if the visualization and the option panel are in the same sub-window

**Comment by zelongjiang123** [comment]
It is fixed #17
