### ISSUE TITLE
Highlight links/joints in 3D scene

### ISSUE THREAD

**Issue by yepw** [uwgraphics/MotionComparator#15]
A robot can have many links/joints, so it's good to highlight the corresponding link/joint when users select or hover over it in the motion library.

**Comment by zelongjiang123** [comment]
Instead of highlighting the link/joint, we add an axisHelper at the position of the link/joint. When the users hover over the robot joint/link button in the selection panel, an axis will be displayed at the position of the corresponding robot joint/link.
